[tool.poetry]
name = "kidsquiz"
version = "0.1.0"
description = ""
authors = ["maral.ashyrova <ashirova310197@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
django = "^4.1.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

